### ISSUE TITLE
(WhishList) Add a manual, from basic level.

### ISSUE THREAD

**Issue by danieagle** [PureSwift/Socket#8]
Hi!  

  Thank you very much for this lib, it looks very 
powerful. Please add a manual showing the first steps: e.g. how to create: addresses, sockets, connections, 
events etc, but at a simple and basic level. The current examples are very confusing. Thank you very much!

God and Mary Bless you and yours,
GrateFull,
Dani.

**Comment by colemancda** [comment]
Sorry this is not an issue, this is a feature request. I respectfully request all feature requests include basic commitments from requesters to contribute at least half of the requested work or changes. Thanks for your interest in this library.
